### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by txsastre** [zipurman/oVIRT_Simple_Backup#10]
Hi, just writing here some instructions that should be included in the documentation.

when installing dependences in 
**3 On oVirt Server**
https://github.com/zipurman/oVIRT_Simple_Backup#steps-to-setting-up-xen-migration-and-backup-scripts

`nfs-common` package is missing, if not you cannot mount NFS volumens, also you receive an "wrong FS file" error and you can spend all the day looking for that.

**4 . on oVirtEngine VM**
once installed the plugin https://github.com/zipurman/oVIRT_Simple_Backup/tree/master/plugin

you should do once installed an in /usr/share/ovirt-engine/ui-plugins/simpleBackup
 
`chmod 777 -R *`

if not, the button "Simple Backup" does not appear in the "ovirt-engine" WebUI

**Comment by zipurman** [comment]
I have added the nfs-common to the docs.

I have also added the following:
chmod 777 /usr/share/ovirt-engine/ui-plugins/simpleBackup* -R

Thanks for the review ;)

Fixed in new version 0.6.4 coming soon

**Comment by txsastre** [comment]
A pleasure to help
