### ISSUE TITLE
WebUI. cannot see Domain & Clusters

### ISSUE THREAD

**Issue by txsastre** [zipurman/oVIRT_Simple_Backup#12]
Hi, I followed your instructions here
https://github.com/zipurman/oVIRT_Simple_Backup/issues/6#issuecomment-376171041

but I still cannot see the Domain and Clusters, 
at this moment I have 
"Storage Domains"
- ovirt-image-repository (image created in the installations process automatically)
- SD-_SYN-NFS (Data)
- SD-SYN-ISO (ISO)

Also I think is related the issue that I cannot see in "Single Backup" option  I cannot see any machine.
![seleccio_025](https://user-images.githubusercontent.com/10468371/37953582-95e3f45a-31a3-11e8-908d-6ca1995692a3.png)

Also, In Restore option I can see the machines, but when selected one to restore I have this error.

![seleccio_026](https://user-images.githubusercontent.com/10468371/37953622-bac625d6-31a3-11e8-8bb7-abd1c8bb13b0.png)

**Comment by zipurman** [comment]
If you dont set your Domain/Cluster in the settings, nothing will work. What do you see if your Settings for Domain/Cluster? If you see them listed, click Save one more time in Settings. 

If not, I will write a bit of code to debug your issue.

**Comment by zipurman** [comment]
If you download the latest version 0.6.4, then go to settings and click the "Click Here" at the top. Let me know what you see. Check your apache logs for any errors.

**Comment by txsastre** [comment]
Hi. Nothing is shown in the list, so i cannot choose anything.

At this moment my development cluster is down. Hope I can test tomorrow.

thanks for your efforts

**Comment by txsastre** [comment]
hi, here you are.

![seleccio_027](https://user-images.githubusercontent.com/10468371/38024806-5184d502-3286-11e8-876d-bb5bb7987e5f.png)

**Comment by txsastre** [comment]
by the way, once executed this, I cannot go into the settings page again :/

**Comment by txsastre** [comment]
I think those results are incorrect, here are my configuration.

VM
![seleccio_028](https://user-images.githubusercontent.com/10468371/38025016-29f95a70-3287-11e8-9e4b-f4e937356b8e.png)

Clusters
![seleccio_029](https://user-images.githubusercontent.com/10468371/38025019-30339c34-3287-11e8-9724-36f9525ee2b2.png)

Domains
![seleccio_030](https://user-images.githubusercontent.com/10468371/38025028-364da678-3287-11e8-9ce8-54bf40a179cb.png)

Disks
![seleccio_031](https://user-images.githubusercontent.com/10468371/38025039-3bef728c-3287-11e8-9e40-d58c848ed045.png)

**Comment by txsastre** [comment]
hi. I've wrote 2 issues because is was not working, but, after rebooting Ovirt-engine and backupEngine, now it seems to be working !

At this moment I'm doing a backup, at this moment is very slowly because the development system is not optimized by now, it will take a long time to perform checks, but at this moment seems right.

As soon as I check I will tell you. 

Thanks again.

**Comment by txsastre** [comment]
This information is OK

![seleccio_037](https://user-images.githubusercontent.com/10468371/38028491-5d7d8734-3293-11e8-8147-c35c123b729f.png)
