### ISSUE TITLE
Exporting VM Xenserver - wrong name

### ISSUE THREAD

**Issue by txsastre** [zipurman/oVIRT_Simple_Backup#13]
when exporting I have to set a new name to the exported machine, I set xt-php-XS, but I can see that the name in /mnt/migrate is "xen1.img"

also I cannot select a Cluster where to restore (but I think this is retated to another open issue"

![seleccio_023](https://user-images.githubusercontent.com/10468371/37953265-b33f21f6-31a2-11e8-8d39-e0436580518b.png)

Thanks

**Comment by zipurman** [comment]
If you are migrating a Xen VM, it will use an image of xen1.img, xen2.img, etc for the disks as the migration is just that ... a migration. The names of the img files dont matter and once migrated they can be deleted.

The cluster issue is related to your Engine integration, something still missing on your end, I will comment in the Settings thread you have opened.
