### ISSUE TITLE
xenserver migrate VM - start ?

### ISSUE THREAD

**Issue by txsastre** [zipurman/oVIRT_Simple_Backup#15]
once the migration is done, this VM is stopped, deattached copied disk, and attached to the original VM, 
it's possible to start again the VM migrate machine ? if not it remains stopped.

thanks

**Comment by zipurman** [comment]
There is an option for that on the migrate screen ;)

**Comment by txsastre** [comment]
Ups! Sorry. I've read too quick and thought it was to start the migrated machine
