### ISSUE TITLE
minor visual issue. Disk size wrong

### ISSUE THREAD

**Issue by txsastre** [zipurman/oVIRT_Simple_Backup#16]
in the single backup options, de "disk" size column shows wrong information
![seleccio_034](https://user-images.githubusercontent.com/10468371/38031436-7ba2bede-329b-11e8-981c-f40addf88331.png)

**Comment by zipurman** [comment]
Interesting .... what are the actual disk sizes for these?

**Comment by txsastre** [comment]
hi, the information about the disk is this one.

size are 10GB or 20GB

![seleccio_001](https://user-images.githubusercontent.com/10468371/38053677-0e89f242-32d5-11e8-8aa9-083c48aa05ec.jpg)

**Comment by zipurman** [comment]
K, this issue should now be fixed as it was showing actual_size and not provisioned_size so if thin provisioned, the disk can be quite a bit smaller. If you download and replace:

/server/area/backup.php 
/server/area/scheduled.php.
