### ISSUE TITLE
BackupEngine MUST not have snapshots

### ISSUE THREAD

**Issue by txsastre** [zipurman/oVIRT_Simple_Backup#17]
As you told me, I think it would be very helpfull to write down this advertising on the documentation, its another pretty way to lose days with this issue =P

`BackupEngine MUST not have snapshots`

**Comment by zipurman** [comment]
I already added this to the software to self-detect and alert.

**Comment by txsastre** [comment]
thanks, I  deleted all the snaphost before upgrading, so I couldn't see the alert.
