### ISSUE TITLE
Restore Error.

### ISSUE THREAD

**Issue by txsastre** [zipurman/oVIRT_Simple_Backup#18]
Once backup is working well ;)

I tried a restore and its not working as expected.

1- select VM to restore. Adjust parameters and OK
2- Disk is done 100% a pop up appears "the vm should be restored . you will have to manually confirm the memory... "  and OK, but nothing else appears to confirm anything... isn't it the first step ?
3- I can see that the system is doing stuff with a disk, creating and attaching 
![seleccio_028](https://user-images.githubusercontent.com/10468371/38204144-f13b5dc2-36a1-11e8-9e2f-1c2f65d9d875.png)
4- and finally fail what was it doing.
![seleccio_029](https://user-images.githubusercontent.com/10468371/38204155-fd1257b8-36a1-11e8-9153-9298a3614b2f.png)

once it has failed I have investigated and tried the following stesps 
a- I searched in Storage->Disks and I found the disk it was restored
![seleccio_030](https://user-images.githubusercontent.com/10468371/38204185-21ee07c6-36a2-11e8-991d-5e8256026ddb.png)
b- I attached to a new VM
c-started it, but the VM does not boot :(

![seleccio_031](https://user-images.githubusercontent.com/10468371/38204251-7baf038c-36a2-11e8-9898-2b58b772f941.png)

so by now, I can do backups, but I cannot restore them, I'm at 50% ;)

**Comment by zipurman** [comment]
Try again with latest version as there have been some fixes.

**Comment by txsastre** [comment]
hi there.
I should have to reinstall oVirt again because I was testing XCP-ng with XO on my development servers.
Next week I will install 1 of the 3 servers with oVirt, 1 server is enough to test backup and restores :)

Thank you !

**Comment by txsastre** [comment]
hi again. I'm testing again oVirt 4.2.6 and  oVirt Simple Backup (WebGUI) - Version: 0.6.24 

still having the same issue, I can migrate but when I want to start, seems that there is no OS, it doesent matter the original OS (debian, windows) all of them made the same error.

I remember to use this correctly and also imported windows 2012 from xenserver to ovirt, I think I'm missing something.

**Comment by txsastre** [comment]
well I have found my notes on twitter https://twitter.com/txsastre/status/984402686027157504

gonna try removing first the xentools.

**Comment by zipurman** [comment]
Odd. I just installed a new oVirt setup with 3 hosts. The backup worked right away without issue. Also import/export of xen works.

I do know, that all it takes is the smallest adjustment in the ovirt setup, and nothing will work. 

BTW, I use virtio and not virtio-scsi without issue.

**Comment by zipurman** [comment]
Also, make 100% sure that both XEN and OVIRT are using the "SAME" target for /mnt/migrate if you are migrating.

**Comment by txsastre** [comment]
that was the problem. now its working fine.
thanks !
