### ISSUE TITLE
xen_migrate.sh not found

### ISSUE THREAD

**Issue by txsastre** [zipurman/oVIRT_Simple_Backup#19]
there's a problem in the documentation.

when wget https://raw.githubusercontent.com/zipurman/oVIRT_Simple_Backup/master/xen_migrate/xen_migrate.sh

I've searched it, and its in https://github.com/zipurman/oVIRT_Simple_Backup/blob/master/BashVersion/OtherTools/xen_migrate/xen_migrate.sh

also
`chmod +e xen_migrate.sh`
+e is not a valid parameter shouldn’t it be +x ? 

it does not find the file.

**Comment by zipurman** [comment]
That script is only required by the BASH version which I am no longer supporting> I updated the docs and removed those lines. This is not required for the PHP version.
