### ISSUE TITLE
VMs with Multiple Disks - Backup/Restore Not Yet Supported

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [zipurman/oVIRT_Simple_Backup#2]
Hello.

Your project looks very interesting.
From https://github.com/zipurman/oVIRT_Simple_Backup/blob/master/webUI/README.md

> VMs with Multiple Disks - Backup/Restore Not Yet Supported

When can I expect this functionality? There is a road map?

**Comment by zipurman** [comment]
The additional feature wouldn't be that hard to do, I would expect I will have that working within the next month or so ;)

**Comment by zipurman** [comment]
This option is now added. Let me know of any issues.

**Comment by zipurman** [comment]
This option is ONLY available on the WebUI Plugin Version BTW. I dont plan on adding this to the BASH version.
