### ISSUE TITLE
Automated Backup tries to access /dev/sr0 and fails

### ISSUE THREAD

**Issue by Squeakz** [zipurman/oVIRT_Simple_Backup#20]
#### Expected behaviour

auto backup php file will ignore cdrom devices

#### Actual behaviour

{"status":1,"reason":"Imaging Disk \/mnt\/backups\/FILESRV01\/db499873-c33a-4035-b8f6-7670767c8b7d\/ovirt_20180404_085751\/progress.dat","progress":0,"numberofdisks":2,"thisdisk":""}fdisk: cannot open /dev/sr0: Permission denied

#### Steps to reproduct the behaviour

su apache
php /var/www/html/automatedbackup.php
script hangs trying to access /dev/sr0

**Comment by zipurman** [comment]
Adding the apache/httpd/www-data, which ever user that apache2 runs as to the cdrom group fixes this. Some wise man told me this ... oh yeah, that was you ;)
