### ISSUE TITLE
Backup Failed. Disk not attached

### ISSUE THREAD

**Issue by txsastre** [zipurman/oVIRT_Simple_Backup#21]
When trying to do a backup I receive this error

```

[2018-04-07:22:46:52] Backup Imaging - /0 - 0% Disk Not Attached
[2018-04-07:22:44:18] Backup Imaging - /0 - 0% Disk Not Attached
[2018-04-07:22:44:17] Attaching Image - Disk(s) Attached
[2018-04-07:22:44:08] Creating Backup Paths - Directories Available
[2018-04-07:22:43:55] Creating Snapshot
[2018-04-07:22:43:54] Starting Backup ... 83fbd444-b049-4624-ad5d-48f6baf6128e dummy-debian9
[2018-04-07:22:43:54] ------------------------------------------------------
```

**Comment by zipurman** [comment]
Something must not be configured correctly. 
Do an:

watch "fdisk -l | grep Disk"

on the BackupEngine VM.

Then run the backup and watch what the disks do. Does the second disk get mounted?

If the disk is not attached, then try looking at the following on the oVirt Engine as well:

tail /var/log/ovirt-*/*.log -f

Then run backup and watch for errors.

**Comment by zipurman** [comment]
** What OS are you using for the VM? What Version? Debian 9? CentOS7?

**Comment by zipurman** [comment]
BTW - I am working on a Debian 9 installer - just testing it now. That may be what works best. Also going to add a diagnostic area in the settings to try and test all required areas of the OS are functioning.

**Comment by zipurman** [comment]
You can test the new installer here. Keep in mind, its new, but I just did a fresh install of Debian-9-64bit with 4GB Ram and 2GB disk (1.5GB/ and .5Gswp) and then used installer. After completed all worked fine without any further adjustment. Keep in mind this script does not alter the oVirt Engine, so if there are issues on the Engine they will have to be dealt with manually.

https://github.com/zipurman/oVIRT_Simple_Backup/tree/master/server/site/installer

*** Also, the Xen part of the installer is not done so just ignore the Xen part for now. This installer should assist you with finding if it is your VM or if it is the Engine that is your issue.

Good luck ;)

**Comment by txsastre** [comment]
hi, good morning here.
gonna try the installer, by the way I checked before writing the issues and there where no attached disk while trying to do the backup.

send feedback in a few minutes. thanks !

**Comment by txsastre** [comment]
hi, tested the installer, real great improvement.
a minor issues with instalation.
- I had to insert my allowed IP in allowed_ip.php
- I had to restart the ovirt engine user ovirt-aaa-jdbc-tool user unlock admin

but still no working, I already had this issue, its saying that is making a backup, but when I go to /mnt/backups or try to restore I can see that there is no disk created.

![seleccio_043](https://user-images.githubusercontent.com/10468371/38465025-1fe14ab4-3b17-11e8-97fe-53cf9a0884b9.png)

![seleccio_044](https://user-images.githubusercontent.com/10468371/38465029-3153199e-3b17-11e8-9340-4ac65929e2f1.png)

**Comment by txsastre** [comment]
I'm using Debian 9. ovirt is 4.2.2, ovirt-guest-agent is 1.0.13 (testing) as 1.0.12 was having issues.
watch "fdisk -l | grep Disk" does not bring me anything.

I've reinstalled the ovirt-node and  the backup vm (yours).
I'm gonna try to install from scratch the ovirt-engine

another thing, the server has 4 NICs, each one has an IP and there is no bonding created yet. Do you think could be something related to that ? 

the ovirt-engine at this moment is located inside my XenServer pool, should I try to move it to the ovirt pool as a hosted-engine (I havent tried that yet)

Both pools at this moment are about 1km one of the other connecter by fiber 1Gb

well, gonna try to create a new ovirt-engine, then moving it, if its not working, monday I will try to use another server/Pc as a ovirt-node

by now that's all that is coming to my head.

**Comment by zipurman** [comment]
If you are running your oVirt Engine VM on Xen Server as a VM ... that may very well be the issue. I am 99% sure that isnt supported. I would suggest installing oVirt as a Hosted Engine Install on a single box. I wouldnt recommend using NODE as I have seen many people having issues with it.

You can use my guide here:

http://zipur.ca/knowledgebase/ovirt-4-2-x-hosted-engine-setup-centos7/

**Comment by zipurman** [comment]
I updated the installer to avoid the 2 issues you outlined with allowed_ip and "ovirt-aaa-jdbc-tool user unlock admin". It can still lock you out, now will not try to talk to the API until the uuid_backup_engine has been defined in settings.

**Comment by txsastre** [comment]
hi there. I reinstalled everything from scratch and configured the ovirt-engine hosted.
and now it works as expected !

I tried a backup and a restore, it works

great ! :)
