### ISSUE TITLE
VM HD not detaching from host during conversion

### ISSUE THREAD

**Issue by pslaw** [zipurman/oVIRT_Simple_Backup#24]
#### Expected behaviour
 Xen Detach VM HD from source and attach to VMMigrate server in the XEN environment. The convert VM HD for import in to Ovirt.

#### Actual behaviour
Script does not detach the HD from the source VM. It then turns the source VM back on. Source HD is not attaching to VMMigrate VM. It then attempts to image the HD resulting is the following messages 6 times per second.
[2018-05-28:16:12:13] Xen - Imaging - 0/1 - 0% Disk Not Attached
[2018-05-28:16:12:13] Xen - Imaging - 0/1 - 0% Disk Not Attached
[2018-05-28:16:12:13] Xen - Imaging - 0/1 - 0% Disk Not Attached
[2018-05-28:16:12:13] Xen - Imaging - 0/1 - 0% Disk Not Attached
[2018-05-28:16:12:13] Xen - Imaging - 0/1 - 0% Disk Not Attached
[2018-05-28:16:12:13] Xen - Imaging - 0/1 - 0% Disk Not Attached

#### Steps to reproduct the behaviour
Create Server in XEN as migration host with attached NFS storage. 
Create Backup Server in Ovirt and mount both migrate and backup NFS Storage.
Supply UUID for Backup Server from Ovirt and supply UUID of VMMigrate server from XEN in setup.
Run migration from VM listed in Simple_Backup.
Source VM is stopped, drive does not detach. Server starts back up and logs show as Disk Not Attached.

**Comment by zipurman** [comment]
On the Xen source VM, do you get any errors if you try to manually disconnect the storage using XenCenter?

**Comment by pslaw** [comment]
Just attempted and it detaches successfully with Xencenter. Are there logs in the app I can examine? Thank you for this tool, it is really needed in the community.

**Comment by zipurman** [comment]
Try shutting down the XenServer Source VM prior to running the migration. It is possible that Xen isnt shutting down the VM quickly enough and something is stopping the disconnecting of the disks. Let me know if that changes anything.

You could check the XEN logs on your XenHost as that is where the requests are sent. The request will be for a "vbd-destroy" as the VBD is the binding of the disk to the VM.

Happy to contribute :)

**Comment by pslaw** [comment]
That did it!. Converted. However, now I'm getting a Dracut emergency shell.  I am testing the conversion on a CentOS 7 VM. Not sure if thats the reason why 

/dev/cl/root does not exist
/dev/cl/swap does not exist
/dev/mapper/cl-root does not exist

**Comment by zipurman** [comment]
You used CentOS as your OS for the VM doing the cloning? If so, that is untested as CentOS/RHEL do some things differently.

If the VM for cloning was Debian and you were cloning a Xen-CentOS-VM that has Emerg.Shell then let me know and I will try to replicate.

**Comment by pslaw** [comment]
Both BackupEngine and VM Migration servers are Debian 9.4. I am attempting to clone a Xen-CentOS VM. 

Thanks again for all the help.

**Comment by zipurman** [comment]
No problem.

Let me know exactly what specs you have on your CentOS VM and I will install a new VM on my systems and see if I have similar issue..

EXACT CentOS Version, 64bit?, RAM, CPU, Disk(s), Type of Disk(s), etc.

**Comment by pslaw** [comment]
Minimum Install CD - CentOS 7.4
CentOS Linux release 7.4.1708 (Core) 64bIT
2 Cores
4GB Memory
40GB Base Volume

**Comment by zipurman** [comment]
What did you setup for partitions/swap?

**Comment by pslaw** [comment]
I use the "Entire disk option" which it then creates the LVM.

![capture](https://user-images.githubusercontent.com/39711602/40789164-bf6f64a4-64bf-11e8-97b5-d36db958dd64.PNG)

**Comment by zipurman** [comment]
Found some new issues in the Xen migration part that I need to fix. I hope to have resolved in the next day or so.

**Comment by zipurman** [comment]
You should be able to fix your CentOS import by doing the following on the new CentOS VM in oVirt:

1. Shutdown the VM
2. Edit the VM and set the boot to 1.CD Rom 2.HDD and then attach the Boot ISO to the CDRom for CentOS7
3. Boot the VM and select the Toubleshooting - Rescue - and then option 1
4. On command line type:

chroot /mnt/sysimage
cd /boot
dracut -f
grub2-mkconfig -o /boot/grub2/grub.cfg
exit
shutdown 0 -h

5. Edit the VM again and remove the boot CD and return the boot options to normal, save.
6. VM should now boot.

I am trying to get this process automated, but doing this from Debian to CentOS on the fly is not so easy ;)
