### ISSUE TITLE
How to integrating oVIRT-Simple-Backup in my product as an ISO installer

### ISSUE THREAD

**Issue by adofirst2018** [zipurman/oVIRT_Simple_Backup#25]
I want to integrating oVIRT-Simple-Backup in my hosted-engine ISO installer,  only to provide a iso to customers,  I want to follow hosted-engine setup but this is complex, have you some good advise?

**Comment by zipurman** [comment]
I would recommend that you create a VM with the BackupEngine on it, with defaults that match your ISO installer environment. Then add that VM to your image.iso and write a POST install script that adds the VM to the newly installed hosted-engine. This is not a trivial task, but it should be achievable ;)

You could also add the VM to your own SFTP site and then have the POST hosted-engine installer pull the VM down.
