### ISSUE TITLE
dettach vm snapshot, but /dev/vdb is not deleted

### ISSUE THREAD

**Issue by adofirst2018** [zipurman/oVIRT_Simple_Backup#26]
I use centos7.0 as my engine backup server, when I backup a vm, first attach this vm snapshot, then can find  a /dev/vdb in backup server, when dettach this vm snapshot, but /dev/vdb is not deleted. this question should how to solute?

**Comment by zipurman** [comment]
Sorry for the delay in reply. Not sure what the issue is, but I know there are issues with using CentOS and disks vs using Debian. I would recommend creating your backupVM as a debian VM to use this solution.
