### ISSUE TITLE
For security reason, framing is not allowed

### ISSUE THREAD

**Issue by kast88x** [zipurman/oVIRT_Simple_Backup#27]
After login to Ovirt webUI, this message appeared:
https://ibb.co/n0nkse
when i click ok. then it will go to github page, namely:
https://test-engine.domain.int/ovirt-engine/webadmin/plugin/simpleBackup/start.html
https://ibb.co/cTi8Ce
how to fix it?

**Comment by zipurman** [comment]
I have not tried to install in the latest 4.2.5 release, so it is possible this is a new issue as I know they have made some changes to the web API. I will try installing into a new install soon to see if I have a similar issue.

What version of ovirt do you have installed? 

Is your backup engine installed on a debian VM?

Did you install using the installer script, or did you install manually?

What do you have for content in this file from the engine:
- /usr/share/ovirt-engine/ui-plugins/simpleBackup.json

**Comment by kast88x** [comment]
sorry for late reply

Debiad 9 - backupvm
oVirt 4.2.5.2-1.el7 - engine

{
"name": "simpleBackup",
"url": "/ovirt-engine/webadmin/plugin/simpleBackup/start.html",
"config": {
"mainBackupPage": "//${backupengineip}/index.php"
},
"resourcePath": "simpleBackup"
}

This warning appears at the end of the script job

...
Updating Cron Jobs
Setting Default Configs

cp: cannot stat '/var/www/html/plugin': No such file or directory

*** Setting Up Plugin for oVirt Web UI ***

Updating oVirtEngine

Redirecting to /bin/systemctl restart ovirt-engine.service

I copied the "plugin" folder to /var/www/html/ manually, directly from "https://github.com/zipurman/oVIRT_Simple_Backup/tree/master/plugin"

**Comment by zipurman** [comment]
WIth the file : /usr/share/ovirt-engine/ui-plugins/simpleBackup.json  ... you need to make sure it looks like this, but with your IP address in the file:
https://github.com/zipurman/oVIRT_Simple_Backup/blob/master/plugin/simpleBackup.json

There must be something on Debian 9 that is failing on the installer, only tested on Jessie(Debian 8)

Have a look through the installer script and make sure each instruction worked. I can see by what you pasted above that "${backupengineip}" didn't resolve correctly, which means either sed is broken or something else is failing.

I will also add it to my list to launch a Debian9 VM and install the installer and see what happens so I can fix it.

**Comment by zipurman** [comment]
Actually, just looked at my notes and I did test on Deb9. Not sure where it broke, but I will try with the latest repo version of 9 and let you know what comes up.

**Comment by kast88x** [comment]
the address is correct, it just shows the github page at the ovirt-engine fqdn:
https://test-engine.domain.int/ovirt-engine/webadmin/plugin/simpleBackup/start.html

change of ip-address in simpleBackup.json to the backupvm ip-adress did't help

**Comment by zipurman** [comment]
Looks like maybe sshpass isnt installed. Thought I had added that to the docs.

If you followed the instructions, roll back to the snapshot before the install on the backup engine vm.

Then: 

apt-get install sshpass

Then try running the script again.

**Comment by kast88x** [comment]
all the necessary packages were installed before running the script
I'll wait for your test on new versions of Debian and oVirt-engine

script job output https://pastebin.com/ygHmrx5j

**Comment by zipurman** [comment]
I have updated the code as there were a couple small issues that created bigger problems. I did do a fresh install after and all seems to work. Give it another fresh install from your Snapshot and let me know.

**Comment by kast88x** [comment]
The installation runs without errors,  but now I don't see "Simple Backup" in ovirt navigate panel.

**Comment by kast88x** [comment]
And vmbackup can't connect to the oVirt Cluster without specify connection errors

**Comment by zipurman** [comment]
On your engine VM:

- What is in the file /usr/share/ovirt-engine/ui-plugins/simpleBackup.json
- What is in the folder /usr/share/ovirt-engine/ui-plugins/simpleBackup
- Try running these commands on the engine VM as root

```

chmod 755 /usr/share/ovirt-engine/ui-plugins/simpleBackup* -R 

engine-config -s CORSSupport=true 

engine-config -s CORSAllowedOrigins=*  

service ovirt-engine restart

```

Does that change anything?

**Comment by zipurman** [comment]
On ubuntu it wasnt installing apache2 with php - I have added apache2 to the installer to make sure it isnt missed. Check to make sure apache2 is running on your backupvm by:

service apache2 status

If it isnt installed, I would recommend starting from your last snapshot and trying to install again.

**Comment by kast88x** [comment]
# cat /usr/share/ovirt-engine/ui-plugins/simpleBackup.json
{
"name": "simpleBackup",
"url": "/ovirt-engine/webadmin/plugin/simpleBackup/start.html",
"config": {
"mainBackupPage": "//${backupengineip}/index.php"
},
"resourcePath": "simpleBackup"
}


# ll /usr/share/ovirt-engine/ui-plugins/simpleBackup
ls: cannot access /usr/share/ovirt-engine/ui-plugins/simpleBackup: No such file or directory

# ll /usr/share/ovirt-engine/ui-plugins/
total 4
lrwxrwxrwx. 1 root root  48 Aug 16 17:57 dashboard.json -> /usr/share/ovirt-engine-dashboard/dashboard.json
lrwxrwxrwx. 1 root root  53 Aug 16 17:57 dashboard-resources -> /usr/share/ovirt-engine-dashboard/dashboard-resources
-rwxr-xr-x. 1 root root 188 Aug 21 10:42 simpleBackup.json



these commands executed without errors


apache2 running on vmbackup

**Comment by zipurman** [comment]
You must install sshpass before running the script. 

The fact that your json file contains "mainBackupPage": "//${backupengineip}/index.php" instead of "mainBackupPage": "//xxx.xxx.xxx.xxx/index.php" would suggest that ssh pass wasnt installed. Many things wont work without sshpass as it is what is being used in the script to login to the engine to install the plugin.

**Comment by kast88x** [comment]
sshpass installed on vmbackup, it can be seen in script output

**Comment by zipurman** [comment]
Yes, but it needs to be installed prior to the script running.

**Comment by kast88x** [comment]
sshpass was installed manually before the script was run

**Comment by zipurman** [comment]
Not sure of the issue and what is causing it. I have followed the instructions on a fresh new install and all worked as expected. 

- Were you able to login to the engine as root using ssh from the backupVM?
- Did you - Navigate to your new install at https://FQDNofYourBackupEngine and accept the SSL certificate
- On the EngineVM, you are running the script as root user right?
- make sure /etc/ssh/sshd_config has "PermitRootLogin yes"

**Comment by zipurman** [comment]
If you want me to have a look directly at your setup, I would be willing to ssh in and have a look. 

If interested, contact me on the IRC channel. (irc.oftc.net) #ovirt
