### ISSUE TITLE
nfs-common needed

### ISSUE THREAD

**Issue by txsastre** [zipurman/oVIRT_Simple_Backup#28]
hi !
when executing the script is asked and NFS volume for the backup.

is needed that the package **nfs-common** has to be installed before the script, if not an error is received.

cheers !

**Comment by zipurman** [comment]
You are right. That is installing later in the script, but then some calls were added near the top of the script that also require nfs-common. Good catch, will update script.

**Comment by txsastre** [comment]
thanks to you !
