### ISSUE TITLE
restore thin provisioning fail on FC storage

### ISSUE THREAD

**Issue by txsastre** [zipurman/oVIRT_Simple_Backup#29]
I have created VM in thin provisioning on a FC storage, a small one, a Debian with 10GB of disk, once created it uses 3GB more or less.

I have made a backup of this VM, everything OK.

When restoring to the same FC storage, I cannot do it in provisioning state, If I try it does the restore, but I can see the machine but the disk is not there, so it does not start.

If I restore the VM with provisioning it works.

**Comment by zipurman** [comment]
So when restoring, if its a thin provisioned backup, you'd have to set Thin Provisioning: YES on the restore screen. I dont have it self-detecting. Is that what you mean?

**Comment by txsastre** [comment]
nope :)

First, I backuped up a VM

then I restore : 
1 - if I choose "provisioned" -> OK
2 - if I choose "thin provisioned" -> Error, VM appears, but no disk.

**Comment by zipurman** [comment]
When you did the original backup, was it of a thinly provisioned VM?

**Comment by txsastre** [comment]
yes, it was 10GB but real used size is 1GB
