### ISSUE TITLE
PLEASE DELETE ALL SNAPSHOTS AND TRY AGAIN

### ISSUE THREAD

**Issue by dark4rest** [zipurman/oVIRT_Simple_Backup#30]
Reboot your BackupEngineVM - Disks Out Of Order. 
I`m rebooting VM, but nothing change.

**Comment by zipurman** [comment]
Make sure there are no snapshots on the BackupEngineVM. If still getting this error, what is the output of the following commands on the BackupEngineVM (as root)?

fdisk -l

cat /etc/debian_version

df -h

**Comment by dark4rest** [comment]
I'm sure the virtual machine does not have snapshots/


root@srv085:~# fdisk -l
Disk /dev/sda: 20 GiB, 21474836480 bytes, 41943040 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x9606ff12

Device     Boot    Start      End  Sectors Size Id Type
/dev/sda1  *        2048 37750783 37748736  18G 83 Linux
/dev/sda2       37752830 41940991  4188162   2G  5 Extended
/dev/sda5       37752832 41940991  4188160   2G 82 Linux swap / Solaris


root@srv085:~# cat /etc/debian_version
9.5

root@srv085:~# df -h
Filesystem                   Size  Used Avail Use% Mounted on
udev                         959M     0  959M   0% /dev
tmpfs                        194M   20M  174M  11% /run
/dev/sda1                     18G  1.2G   16G   7% /
tmpfs                        969M     0  969M   0% /dev/shm
tmpfs                        5.0M     0  5.0M   0% /run/lock
tmpfs                        969M     0  969M   0% /sys/fs/cgroup
srv021:/mnt/backup/vmbackup   17T  3.0T   14T  19% /mnt/backups
tmpfs                        194M     0  194M   0% /run/user/0

**Comment by zipurman** [comment]
That all looks good, paste the output of the following:

cat /var/www/html/config.php

**Comment by dark4rest** [comment]
root@srv085:~# cat /var/www/html/config.php
<?php
$settings = array(
"vms_to_backup" => array(""),
"label" => "bcp_",
"uuid_backup_engine" => "5e392dd3-ccb1-4fe8-a68b-f53bf0358ff9",
"ovirt_url" => "ovhe.domain.lan.com(not real name)",
"ovirt_user" => "admin@internal",
"ovirt_pass" => "Pasword(not real password :) )",
"mount_backups" => "/mnt/backups",
"drive_type" => "",
"drive_interface" => "",
"backup_log" => "/var/log/simplebackup.log",
"email" => "",
"retention" => 2,
"storage_domain" => "",
"cluster" => "",
"mount_migrate" => "/mnt/migrate",
"xen_ip" => "",
"xen_migrate_uuid" => "",
"xen_migrate_ip" => "",
"restore_console" => "vnc",
"restore_os" => "other_linux",
"restore_vm_type" => "server",
"restore_cpu_sockets" => "2",
"restore_cpu_cores" => "2",
"restore_cpu_threads" => "1",
"tz" => "Europe/Moscow",
);

**Comment by zipurman** [comment]
There is the issue. Go to the settings tab and select all of your settings, and then save. Several of your settings are empty in the config. By saving in the settings it should save them to the config file.

**Comment by zipurman** [comment]
I will add a feature to the software to better handle this situation and the original setup of the admin settings. Watch for the new version ;)

**Comment by zipurman** [comment]
feature added to latest version to better identify the issue and lead users to finding the solution. The previous version would allow you to not save the settings for domain, cluster etc and would still show the links to backup etc. You cannot backup until you save these settings, so you would end up with errors.
