### ISSUE TITLE
ovirt guest agent

### ISSUE THREAD

**Issue by dark4rest** [zipurman/oVIRT_Simple_Backup#31]
If on backupEngineVm installed oVirt Guest Agent - not saving settings.  After push Save button displaying message Reboot your BackupEngineVM - Disks Out Of Order. If BackupEngineVm without oVirt Guest Aget - working fine.

**Comment by zipurman** [comment]
You should install the guest agent using this method on Debian:

http://zipur.ca/knowledgebase/debian-8-jessie-ovirt-guest-agent/

**Comment by dark4rest** [comment]
Yes! It's work! Thank you!
