### ISSUE TITLE
Is there any chance to do snapshot of Virtual Machines without memory?

### ISSUE THREAD

**Issue by Marcin13666** [zipurman/oVIRT_Simple_Backup#32]

**Comment by humnab** [comment]
I did it this way in /var/www/html/comm/snapshot_status.php:

`$xml = '<snapshot>
                                        <description>' . $snapshotname  . '</description>
                                        <persist_memorystate>false</persist_memorystate>
                                      </snapshot>';
`

**Comment by zipurman** [comment]
Not a bad idea, will add that option. ;)

**Comment by Marcin13666** [comment]
thanks

**Comment by zipurman** [comment]
Feature added. Let me know if any issues.
