### ISSUE TITLE
Error when attaching disk with QOS on storage

### ISSUE THREAD

**Issue by Marcin13666** [zipurman/oVIRT_Simple_Backup#34]
#### Expected behavior
When you run backup on VM hard drive (snapshote) should be attached to VM and backup should start
#### Actual behaviour
When you run backup on VM hard drive (snapshote) is not attached to VM, Error:
```VDSM vmname.domain command HotPlugDiskVDS failed: General Exception: ("Unsupported {u'write_bytes_sec': 5242880, u'total_iops_sec': 0, u'read_iops_sec': 100, u'read_bytes_sec': 62914560, u'write_iops_sec': 10, u'total_bytes_sec': 0} for ioTune",)```

#### Steps to reproduce the behavior
Create a VM
Create a QOS and storage profile:
->Compute -> Data Centers -> Click on datacenter -> QOS tab -> create new storage QOS with limitation of Read Write and IOPs:
Storage -> Storage Domains -> click on storage domain name -> Disk Profiles tab -> associate QOS with profile
Attach storage profile to VM drive:
Compute -> Virtual Machines -> VM name -> Disks Tab -> click "edit" disk and change  Disk profile
Start Backup

#### Solution
Remove QOS profile from snapshot or if possible try to mount it in different way

**Comment by zipurman** [comment]
Thanks for the details, much easier to understand the issue with the right info ;)

This looks to me to be a limitation within oVirt/KVM? I will have to do some digging to see if there is anything I can do through the API that would allow the QOS not to create an "Unsupported" error.

I havent used any of the QOS features of oVirt so far. Will do some tests and let you know if I find a solution.
