### ISSUE TITLE
Doubt Backup

### ISSUE THREAD

**Issue by jeaneduardo** [zipurman/oVIRT_Simple_Backup#37]
Hello

First I would like to congratulate the project.

I have a doubt.

why does not it appear to back up the Hosted VM of oVirt Simple Backup VM?

Regards,

**Comment by zipurman** [comment]
Thanks ;)

The Simple Backup VM cannot backup itself or the HostedEngine. 

You can backup the hosted engine files using this method: http://zipur.ca/knowledgebase/backup-hosted-engine/

**Comment by jeaneduardo** [comment]
Thanks
