### ISSUE TITLE
Buffer I/O error on dev dm-3, logical block 0, async page read

### ISSUE THREAD

**Issue by Marcin13666** [zipurman/oVIRT_Simple_Backup#38]
after disk snapshot that contains LVM is removed from backup appliance we get I/O error as system still see LVM drives and can't access to it.

how to avoid it:
After snapshot is detached run:
`dmsetup remove_all`

To avoid problems with LVM could be nice if you can mention in install manual that groups and LVM names inside the appliance need to be unique, When you create all machines from templates and you have this same name for each lvm VM hangs when you detach snapshot .

**Comment by zipurman** [comment]
I will add the "dmsetup remove_all" as described. Does this get around the issue so that it no longer requires LVM names to be unique? I didnt run into issue and some of my VM's are made from the same templates.

**Comment by Marcin13666** [comment]
you still need to have unique LVMs names, is not bug in your software is the way how OS is working so is why should be only mentioned in installation manual 
Thank you

**Comment by zipurman** [comment]
;) I will add a note to the docs. Thanks for pointing out the issue ;)

**Comment by doe-cu** [comment]
Hello,

I experienced the same problem, the solution that worked for me was to prevent lvm  from scanning any disk other than /dev/sda

in /etc/lvm/lvm.conf add
global_filter = [ "a|/dev/sda|", "r|/dev/sd*|" ]

Seemed simpler than making sure all lvm names are unique.

**Comment by zipurman** [comment]
Thanks doe-cu, I have added your comment to the docs ;) Will post on next push.

**Comment by jivef** [comment]
Hi all,

Sorry it's an old issue, but I had the same today and for information, in my case, it was a RAID controller issue.
I replace the RAID controller with the same model, I imported the configuration of my 8 disks in RAID 5 and now it works.
Sometimes, the problem is the hardware... but for a 11 years old server it's not to bad. :-)
Best regards.
