### ISSUE TITLE
Error with Invalid UUID

### ISSUE THREAD

**Issue by doe-cu** [zipurman/oVIRT_Simple_Backup#39]
After importing some VMs from KVM (via libvirt) the UUID would not match in backup_create_path.php.
example UUID 2712f337-54d7-a781-24cb-53c642e35bff

The solution was to edit reg.php
-      $UUIDv4  = '/^[0-9A-F]{8}-[0-9A-F]{4}-4[0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$/i';
+      $UUIDv4 = '/^[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}$/i';

Other people might experience this issue.

**Comment by zipurman** [comment]
Thanks again doe-cu, I have adjusted the code. The extra strict format was only geared to oVirt's UUID format, this will only make it more flexible ;) Thanks for your imput and I hope the script is working well for you ;)
