### ISSUE TITLE
error SSL. debian 9 . php7

### ISSUE THREAD

**Issue by txsastre** [zipurman/oVIRT_Simple_Backup#4]
hi.
when trying

```
vi /etc/apache2/sites-available/default-ssl.conf

    ServerName backupengine.yourdomain.com:443
    DocumentRoot /var/www/html/site
    SSLCertificateFile /etc/apache2/ssl/apache.crt
```
and after doing all the following steps, I have 2 problems.
if I put the certificate as related, the apache does not start.
otherwise if I don't change the certificate, then navigator (firefox) does not allow me to open than web because is a "self signed certificate" 

using debian 9 . php7

**Comment by txsastre** [comment]
same error with Debian 8 and php 5. I have to set an exception on the Firefox.

**Comment by zipurman** [comment]
Apache should start if the cert is created as /etc/apache2/ssl/apache.crt

Make sure that the /etc/apache2/ssl/apache.crt file exists and that you have set permissions as:
chmod 600 /etc/apache2/ssl/*


The only way you can avoid setting the exception for a self-signed cert, is to purchase a certificate from a trusted CA.

You could also use https://letsencrypt.org/

**Comment by txsastre** [comment]
Thanks again. Ok may be I misunderstood the instructions, I thought that that problem was not expected. So it works fine once I set an exception on the Firefox. 

By the way thanks for the URL, I will try that !.
