### ISSUE TITLE
Invalid error message

### ISSUE THREAD

**Issue by nevesigor** [zipurman/oVIRT_Simple_Backup#40]
#### Expected behaviour
Output something like: Backup data partition it's full.

#### Actual behaviour
Output it's: "Error Creating Backup Directories - Check Permissions to ..."

#### Steps to reproduct the behaviour
Just try to backup something with the backup mount-point full.

**Comment by zipurman** [comment]
There can be many reasons why this error could occur, not always a full hdd. I will add that as one of the possible reasons.

**Comment by nevesigor** [comment]
If it's the reason it's full, should say "Full" at least that one it's covered.

**Comment by zipurman** [comment]
I suppose I could have the code check for available hard drive space and then report as full. The only thing it does now is tests to see if the file is successfully written and if not it shows an error.

**Comment by zipurman** [comment]
I have added this adjustment, will push out changes later today.
Also added some inline warnings on /mnt/backups hdd space if getting low. *Good Idea!*
