### ISSUE TITLE
exclude "lost+found" from restore

### ISSUE THREAD

**Issue by nevesigor** [zipurman/oVIRT_Simple_Backup#42]
#### Expected behaviour
When going to "Simple Backup->Restore" directory "lost+found" should not be show.

#### Actual behaviour
When going to "Simple Backup->Restore" directory "lost+found" from filesystem appears.

#### Steps to reproduct the behaviour
Use the backup data filesystem root as backup mount-point.

**Comment by zipurman** [comment]
I have added this adjustment, will push out changes later today.
