### ISSUE TITLE
Wrong Drive Letter when backup

### ISSUE THREAD

**Issue by nevesigor** [zipurman/oVIRT_Simple_Backup#43]
#### Expected behaviour
DD/PV copy should use the right drive letter.

#### Actual behaviour
If the "simple-backup" VM have more then one disk (sda + sdb), backup process always copy data from sdb, it writes this to the log:

_Disk Dat Write Disk1 - e94e4899-5c88-4a7d-979f-7f98b91f3e82 - true - virtio_scsi - 32212254720 - sdb_

sda /
sdb /var
sdc (disk attached from the VM we are doing the backup)

**NOTE:** this is kind of problem if you intend to use /dev/sdb as attached storage for backup and not NFS mounted.

#### Steps to reproduct the behaviour
Just create SimpleBackup VM with two disks.

**Comment by zipurman** [comment]
Try changing the following in backup_attach_image.php
Line 21 : $diskletter   = 'a';
Change to: $diskletter   = 'b';
to start mounting disks after 'b'

Let me know if that works. I could add a setting to start disk mapping at x.

**Comment by zipurman** [comment]
You will also want to make this change to xen_add_vbd.php(37) and restore)disk_create.php(33) , reg.php(93)

**Comment by nevesigor** [comment]
I think this might not be the right approach, when I attach 10 VMS to backup each with 5 disks this will be a mess of discs in the guest.
Also if it's done two backups at the same time with a lot of discs, it will get a lot of messy.
It's there a way to identify the disks attached by uuid inside simple backup machine? That way was perfect, we would know exactly which disks we were doing the backup from.
Maybe smart attribute? Disk attribute when attaching?

**Comment by zipurman** [comment]
It doesnt work that way. simpleBackup will mount the disks for a given VM, image them, then eject them and move to the next VM to be backed up. There is no issue, as I am backing up many VMs with multiple disks per VM every day. Some people also create clones of VMs, so UUIDs will not be unique, the way I have it works. There is never a case where this script will mount 10 VM's disks all at once.

**Comment by nevesigor** [comment]
So it will not be possible to backup two VM at the same time with this
method?

**Comment by zipurman** [comment]
No. The script will create an array of VMs to be backed up. It will then loop through the array, attaching snapshots and disks as it goes. Once it completes one VM, all the disks are released and it moves on to the next one. If we mounted many VMS disks all at once and imaged all at once ... well that would be a mess.

**Comment by zipurman** [comment]
I have 30+ VMs on a daily schedule. It will back them all up within 90 minutes onto remote NFS. There is no down time as it creates snapshots to do the imaging. It is automated and there is no issue. I then get an email report when it is completed. Is that not what you are looking for?

**Comment by nevesigor** [comment]
That drive letter bypass, for now it's ok, I'm just trying to understand the limitations.

Anyway when you implement the incremental backups you mention today, that will help a lot.

I will test this code tomorrow and let you know.

**Comment by nevesigor** [comment]
The code seems to work in some part, but it breaks in some another point, I'm trying to reach you on IRC, very fuzzy to "chat" over here, let's see if I can find you later today to share my experience.

**Comment by zipurman** [comment]
Have a look at the logs to see where it breaks. I am always on irc.oftc.net:6667 #ovirt
