### ISSUE TITLE
Log file is on Centos is not parsing \n =, each event in this same line

### ISSUE THREAD

**Issue by Marcin13666** [zipurman/oVIRT_Simple_Backup#44]
At the beginning want to say that I use Centos so maybe my problems are related to some package in this operating system.

### Problem
Log file on doesn't parse new line character, each log is written in this same line with "\n" at the end

**Solution:**
edit sb_log function in functions.php, change echo -n to echo -e

`    function sb_log( $logtext ) {

        GLOBAL $settings;
        if ( ! empty( $settings['backup_log'] ) ) {
            $logtext = str_replace( '"', '', $logtext );

            $logtime = strftime( "[%Y-%m-%d:%H:%M:%S]" );

            $logdata = $logtime . ' ' . $logtext;

            //get last line of log
            exec( 'tail ' . $settings['backup_log'] . ' -n 1', $lastlogitem );
            $lastlogitem = $lastlogitem[0];
            $lastlogitem = preg_replace( '/\[[0-9\-:]+\] /i', '', $lastlogitem );

            //dont log if nothing has changed
            if ( ! strpos( " {$lastlogitem}", "{$logtext}" ) !== false ) {
                sleep( 0.5 );
                exec( 'echo -e "\n' . $logdata . '" >> ' . $settings['backup_log'] );
            } else {
                exec( 'echo -e "." >> ' . $settings['backup_log'] );
            }
            sleep( 0.5 );

        }
    }`

**Comment by zipurman** [comment]
The backupVM only supports debian.
