### ISSUE TITLE
Option `First Backup Disk` doesn't work correctly

### ISSUE THREAD

**Issue by Marcin13666** [zipurman/oVIRT_Simple_Backup#45]
When you have more than 1 drive connected to VM:
```
$numberofimages = count( $disktypeget['avaliabledisks'] );
if ( $numberofimages > 1 && empty( $recovery ) ) {
        sb_pagedescription( 'The backup VM has too many disks attached. Please remove all but the OS disk in order to preform a backup.' );
```
Prevent you to do a backup

**Solution:**
```$numberofimages = $numberofimages-$number_of_drives````
You could add the option in settings that will take no only last drive letter but as well how many drive there is in system

**Problem:**
When you use multipathing in your operating system can be a lot of physical drives there is not enough options in setting for this.

Restrictions:
Every drive that is connected to operating system needs to have this same prefix for example sd[X]

**Comment by zipurman** [comment]
BackupVM should only ever have the main drive partition. If you need local storage (USB Backup Drive), there is a way to get that working using the settings and set b,c,d for last disk. VM Disks are mounted and unmounted as the backups are completed.

Mulipathing shouldnt be used within the BackupVM itself.
