### ISSUE TITLE
Post-installation Issues

### ISSUE THREAD

**Issue by pojoguy** [zipurman/oVIRT_Simple_Backup#55]
This is a fresh installation on ubuntu 18.04 LTS and oVirt 4.2, installed using the instructions at https://github.com/zipurman/oVIRT_Simple_Backup/blob/master/README.md?fbclid=IwAR2b1LNnJ1051pCF5AxTHkp_dBvrEwKIQXUQZk5t9y-JgnALf8R5no3yQAk

1. Post installation, I am able to access the oVIRT_Simple_Backup directly on its server, but not from the oVirt controller. the oVirt controller has the "Simple Backup" tab, but it says the IP address cannot be found. I presume the expected behavior is to show the Simple Backup UI.

2. When I access the installed oVIRT_Simple_Backup, and go to "Single Backup", which would suffice for my immediate needs, it tells me "The backup VM has too many disks attached. Please remove all but the OS disk in order to preform a backup." I have only one disk on that VM.

#### Actual behaviour
The backup VM has too many disks attached. Please remove all but the OS disk in order to preform a backup.

**Comment by zipurman** [comment]
Ubuntu is NOT supported.

I would recommend doing the following:

1. On the Engine - run the following as root: "rm /usr/share/ovirt-engine/ui-plugins/simpleBackup* -R"

2. review this page: https://github.com/zipurman/oVIRT_Simple_Backup/blob/master/server/installer/HOWITWORKS.md

3. Delete the SimpleBackupVM, create a new one using the instructions here:
https://github.com/zipurman/oVIRT_Simple_Backup/blob/master/server/installer/README.md

The installer should do everything correctly as long as each step is followed.

**Comment by pojoguy** [comment]
Thank you.

I made a simple typo during installation in Debian 9.9.0
 .
How do I correct the backup server's url without wiping and reinstalling
everything?

Thanks.

**Comment by pojoguy** [comment]
I have followed these directions. There are some issues using the tool with
Firefox (Firefox is extremely strict about SSL certificates), but using
Chrome I am able to make it work.

**Comment by zipurman** [comment]
To fix the server URL in the plugin - edit the file /usr/share/ovirt-engine/ui-plugins/simpleBackup.json

I also use firefox. You can either accept the certificate or you can install a trusted cert in apache for the VM.

**Comment by pojoguy** [comment]
Thank you!
