### ISSUE TITLE
Documentation for migrating Windows machines from XenServer to oVirt

### ISSUE THREAD

**Issue by jameswadsworth** [zipurman/oVIRT_Simple_Backup#57]
While migrating Windows desktops and servers from XenServer to oVirt, while the migration using SimpleMigrate worked very well, we had BSOD issues when booting the machines for the first time on oVirt. Eventually we found the cause and found the necessary steps to resolve these problems. We'd like to share our experience. If we write an article outlining the issue we encounter and the steps we took to resolve, would you publish it on under http://zipur.ca/docs/

**Comment by zipurman** [comment]
For sure. I would also add a link to the page https://github.com/zipurman/oVIRT_Simple_Backup/blob/master/docs/POST_XEN_MIGRATION.md
