### ISSUE TITLE
Cannot Restore - bash edition

### ISSUE THREAD

**Issue by txsastre** [zipurman/oVIRT_Simple_Backup#7]
I tried to restore a machine, but the only thing that is restored is the VM, but not the disk.

as far as I can see, the appliance attaches the disk of the VM I want to restore, its OK.
but it seems that the attached disk is not send to the Datastore, and remain attached to the appliance, so the VM is restored (only the specifications) but no disk attached.

I have investigated the vmrestoresingle.sh file, I noticed that there are value named $newdiskuuid and $newdiskuuid thant does not have value. So when the instruciont `obuattachadisk $newvmuuid $newdiskuuid` is executed nothing happends because the variables are empty.

looks like in line 151 in vmrestoresingle.sh is not receiving the data . checkvm="${obuapicallresult}"

maybe I'm wrong but that's what I have found.

**Comment by zipurman** [comment]
The script works great when all pieces are working as expected. My best guess here is that the disk devices are not loading and matching your setting. You can check using:

fdisk -l | grep Disk

to see what disk you have on the BackupApplianceVM. Should be /dev/vda or /dev/sda, make sure your settings are set to vd or sd accordingly.

I am also working on releasing next version within a few days which has a lot of the code redone. I plan on abandoning the BASH version as the php version works better and will soon have the scheduled backups built into it too.

**Comment by txsastre** [comment]
yes I double checked it, and also tested with "sd" and "vd" changing the dist type from "orivt" and "ovirt_scsi"

same result. but don't worry, as you're planning to abandon the bash version I will not spend more time testing it, I will wait to the new web relase :)
