### ISSUE TITLE
UPDATE COMING

### ISSUE THREAD

**Issue by zipurman** [zipurman/oVIRT_Simple_Backup#8]
NEW VERSION WILL BE READY VERY SOON - BE PATIENT AS IT'LL BE WORTH WAITING FOR!

**Comment by txsastre** [comment]
Hi !
Glad to hear that !! :D 

I have to say that I'm really enjoying testing (oVirt + oVSB) and I see that's going to be the next VM platform we're going to use.

And I can see that oVSB is going to be a very powerful/must tool to use in conjunction with oVirt

If I can help, just tell me.

**Comment by zipurman** [comment]
Update released. Still working on some minor issues. Let me know if you have any questions or concerns.
