### ISSUE TITLE
Minor Issues when installing 

### ISSUE THREAD

**Issue by txsastre** [zipurman/oVIRT_Simple_Backup#9]
the instruction 

` chown www-data:disk /dev/vdb`

return "file o directory does not exist"

the instruction 
`chmod 777 /dev/sr0`
return "file o directory does not exist"

altough the file /webUI/server/site/index.php
(that was reported in another issue)
lacks this code at the beginning, if not the web is seen like the '90s :P
```
<head>
<link rel="stylesheet" type="text/css" href="css/style.css">
</head>
```

**Comment by zipurman** [comment]
I removed the one chown and the chmod, both were attempts to avoid OS errors from some of the other commands. Those workarounds didnt work anyway and I just forgot to remove them.

As for your css comment, not sure what you mean?

**Comment by txsastre** [comment]
Ok thanks.
the css problem was related here 

https://github.com/zipurman/oVIRT_Simple_Backup/issues/5

**Comment by zipurman** [comment]
I think you have some old code somewhere as this shouldnt be an issue any longer.

**Comment by txsastre** [comment]
well I have deleted and uploaded the new php, html, css code.
its an issue but still there 
![seleccio_039](https://user-images.githubusercontent.com/10468371/37880268-c5ce2236-3085-11e8-8eee-d7aeed4caf55.png)

**Comment by zipurman** [comment]
What are you using for settings in plugin/simpleBackup.json?

What is your /etc/apache2/sites-available/default-ssl.conf set to for DocumentRoot?

If you open the plugin in a new tab, (ctrl + click-on-settings). Look at the source of the html and at the style.min.css, what is the full path that it is trying to use to load that file?

**Comment by zipurman** [comment]
Found the issue ... my bad ... I didnt have the auto-minified versions of the css/js added to git. Fixed and updated. Please download the style.min.css and the script.min.js and place them in their directories and this issue should then be resolved.

**Comment by txsastre** [comment]
ok, deleted everything, uploaded again.
now the webUI is seen as expected :)
